# Init

In [ ]:
import numpy as np
import pandas as pd

# Supervised learning

In [ ]:
d = {
     "LR":[ 0.720, 0.836, 0.557, 0.851, 0.748, 0.801, 0.860],
     "XGBoost":[0.726, 0.895, 0.587, 0.912, 0.892, 0.821, 0.925],
     "MLP":[0.643, 0.832, 0.568, 0.904, 0.613, 0.832, 0.893],
     "SNN":[0.641, 0.880, 0.540, 0.902, 0.621, 0.834, 0.892],
     "TabNet":[0.585, 0.800, 0.478, 0.904, 0.680, 0.819, 0.896],
     "DCN":[0.739, 0.870, 0.674, 0.913, 0.848, 0.840, 0.915],
     "AutoInt":[0.744, 0.866, 0.672, 0.913, 0.808, 0.844, 0.916],
     "TabTrans":[0.718, 0.860, 0.648, 0.914, 0.855, 0.820, 0.882],
     "FT-Trans":[0.739, 0.859, 0.657, 0.913, 0.862, 0.841, 0.915],
     "Vime":[0.735, 0.852, 0.485, 0.912, 0.769, 0.837, 0.908],
     "Scarf":[0.733, 0.861, 0.663, 0.911, 0.719, 0.833, 0.905],
     "TransTab":[0.768, 0.881, 0.643, 0.907, 0.851, 0.845, 0.919]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
df.mean(axis=0).sort_values()

AutoInt      3.142857
DCN          3.285714
TransTab     3.428571
FT-Trans     3.714286
XGBoost      4.428571
Scarf        6.428571
TabTrans     6.571429
Vime         6.857143
SNN          8.857143
MLP          9.571429
LR          10.142857
TabNet      10.571429
dtype: float64

In [ ]:
d = {
     "LR":[ 0.720, 0.836, 0.557, 0.851, 0.748, 0.801, 0.860],
     "XGBoost":[0.726, 0.895, 0.587, 0.912, 0.892, 0.821, 0.925],
     "MLP":[0.643, 0.832, 0.568, 0.904, 0.613, 0.832, 0.893],
     "SNN":[0.641, 0.880, 0.540, 0.902, 0.621, 0.834, 0.892],
     "TabNet":[0.585, 0.800, 0.478, 0.904, 0.680, 0.819, 0.896],
     "DCN":[0.739, 0.870, 0.674, 0.913, 0.848, 0.840, 0.915],
     "AutoInt":[0.744, 0.866, 0.672, 0.913, 0.808, 0.844, 0.916],
     "TabTrans":[0.718, 0.860, 0.648, 0.914, 0.855, 0.820, 0.882],
     "FT-Trans":[0.739, 0.859, 0.657, 0.913, 0.862, 0.841, 0.915],
     "Vime":[0.735, 0.852, 0.485, 0.912, 0.769, 0.837, 0.908],
     "Scarf":[0.733, 0.861, 0.663, 0.911, 0.719, 0.833, 0.905],
     "TransTab":[0.738, 0.906, 0.628, 0.904, 0.814, 0.835, 0.913]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
df.mean(axis=0).sort_values()

DCN          2.714286
AutoInt      2.714286
FT-Trans     3.285714
XGBoost      4.571429
TransTab     4.857143
Scarf        6.428571
TabTrans     6.571429
Vime         6.714286
SNN          8.857143
MLP          9.428571
LR          10.142857
TabNet      10.428571
dtype: float64

# Feature incremental learning

In [ ]:
d = {
     "LR":[ 0.670, 0.773, 0.475, 0.832, 0.727, 0.806, 0.825],
     "XGBoost":[0.608, 0.817, 0.527, 0.891, 0.778, 0.816, 0.898],
     "MLP":[0.586, 0.676, 0.516, 0.890, 0.631, 0.825, 0.885],
     "SNN":[0.583, 0.738, 0.442, 0.888, 0.644, 0.818, 0.881],
     "TabNet":[0.573, 0.689, 0.419, 0.886, 0.571, 0.837, 0.882],
     "DCN":[0.674, 0.835, 0.578, 0.893, 0.778, 0.840, 0.891],
     "AutoInt":[0.671, 0.825, 0.563, 0.893, 0.769, 0.836, 0.887],
     "TabTrans":[0.653, 0.732, 0.584, 0.856, 0.784, 0.792, 0.828],
     "FT-Trans":[0.662, 0.824, 0.626, 0.892, 0.768, 0.840, 0.889],
     "Vime":[0.621, 0.697, 0.571, 0.892, 0.769, 0.803, 0.881],
     "Scarf":[0.651, 0.753, 0.556, 0.891, 0.703, 0.829,0.887],
     "TransTab":[0.741, 0.879, 0.665, 0.894, 0.791, 0.841, 0.897]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
print(df)
print(df.mean(axis=0).sort_values())
print(df.std(axis=0).sort_values())

     LR  XGBoost   MLP   SNN  TabNet  DCN  AutoInt  TabTrans  FT-Trans  Vime  \
0   4.0      9.0  10.0  11.0    12.0  2.0      3.0       6.0       5.0   8.0
1   6.0      5.0  12.0   8.0    11.0  2.0      3.0       9.0       4.0  10.0
2  10.0      8.0   9.0  11.0    12.0  4.0      6.0       3.0       2.0   5.0
3  12.0      6.0   8.0   9.0    10.0  2.0      2.0      11.0       4.0   4.0
4   8.0      3.0  11.0  10.0    12.0  3.0      5.0       2.0       7.0   5.0
5  10.0      9.0   7.0   8.0     4.0  2.0      5.0      12.0       2.0  11.0
6  12.0      1.0   7.0   9.0     8.0  3.0      5.0      11.0       4.0   9.0

   Scarf  TransTab
0    7.0       1.0
1    7.0       1.0
2    7.0       1.0
3    6.0       1.0
4    9.0       1.0
5    6.0       1.0
6    5.0       2.0
TransTab    1.142857
DCN         2.571429
FT-Trans    4.000000
AutoInt     4.142857
XGBoost     5.857143
Scarf       6.714286
Vime        7.428571
TabTrans    7.714286
LR          8.857143
MLP         9.142857
SNN         9.428571
TabNet      9.857143
dtype: float64
TransTab    0.377964
DCN         0.786796
Scarf       1.253566
SNN         1.272418
AutoInt     1.463850
FT-Trans    1.732051
MLP         1.951800
Vime        2.760262
TabNet      2.968084
LR          3.023716
XGBoost     3.078342
TabTrans    4.070802
dtype: float64

In [ ]:
d = {
     "LR":[ 0.670, 0.773, 0.475, 0.832, 0.727, 0.806, 0.825],
     "XGBoost":[0.608, 0.817, 0.527, 0.891, 0.778, 0.816, 0.898],
     "MLP":[0.586, 0.676, 0.516, 0.890, 0.631, 0.825, 0.885],
     "SNN":[0.583, 0.738, 0.442, 0.888, 0.644, 0.818, 0.881],
     "TabNet":[0.573, 0.689, 0.419, 0.886, 0.571, 0.837, 0.882],
     "DCN":[0.674, 0.835, 0.578, 0.893, 0.778, 0.840, 0.891],
     "AutoInt":[0.671, 0.825, 0.563, 0.893, 0.769, 0.836, 0.887],
     "TabTrans":[0.653, 0.732, 0.584, 0.856, 0.784, 0.792, 0.828],
     "FT-Trans":[0.662, 0.824, 0.626, 0.892, 0.768, 0.840, 0.889],
     "Vime":[0.621, 0.697, 0.571, 0.892, 0.769, 0.803, 0.881],
     "Scarf":[0.651, 0.753, 0.556, 0.891, 0.703, 0.829,0.887],
     "TransTab":[0.733, 0.896, 0.605, 0.904, 0.822, 0.832, 0.912]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
print(df)
print(df.mean(axis=0).sort_values())
print(df.std(axis=0).sort_values())

     LR  XGBoost   MLP   SNN  TabNet  DCN  AutoInt  TabTrans  FT-Trans  Vime  \
0   4.0      9.0  10.0  11.0    12.0  2.0      3.0       6.0       5.0   8.0
1   6.0      5.0  12.0   8.0    11.0  2.0      3.0       9.0       4.0  10.0
2  10.0      8.0   9.0  11.0    12.0  4.0      6.0       3.0       1.0   5.0
3  12.0      6.0   8.0   9.0    10.0  2.0      2.0      11.0       4.0   4.0
4   8.0      3.0  11.0  10.0    12.0  3.0      5.0       2.0       7.0   5.0
5  10.0      9.0   7.0   8.0     3.0  1.0      4.0      12.0       1.0  11.0
6  12.0      2.0   7.0   9.0     8.0  3.0      5.0      11.0       4.0   9.0

   Scarf  TransTab
0    7.0       1.0
1    7.0       1.0
2    7.0       2.0
3    6.0       1.0
4    9.0       1.0
5    6.0       5.0
6    5.0       1.0
TransTab    1.714286
DCN         2.428571
FT-Trans    3.714286
AutoInt     4.000000
XGBoost     6.000000
Scarf       6.714286
Vime        7.428571
TabTrans    7.714286
LR          8.857143
MLP         9.142857
SNN         9.428571
TabNet      9.714286
dtype: float64
DCN         0.975900
Scarf       1.253566
SNN         1.272418
AutoInt     1.414214
TransTab    1.496026
MLP         1.951800
FT-Trans    2.138090
Vime        2.760262
XGBoost     2.828427
LR          3.023716
TabNet      3.302236
TabTrans    4.070802
dtype: float64

In [ ]:
d = {
     "LR":[ 0.670, 0.773, 0.475, 0.832, 0.727, 0.806, 0.825],
     "XGBoost":[0.608, 0.817, 0.527, 0.891, 0.778, 0.816, 0.898],
     "MLP":[0.586, 0.676, 0.516, 0.890, 0.631, 0.825, 0.885],
     "SNN":[0.583, 0.738, 0.442, 0.888, 0.644, 0.818, 0.881],
     "TabNet":[0.573, 0.689, 0.419, 0.886, 0.571, 0.837, 0.882],
     "DCN":[0.674, 0.835, 0.578, 0.893, 0.778, 0.840, 0.891],
     "AutoInt":[0.671, 0.825, 0.563, 0.893, 0.769, 0.836, 0.887],
     "TabTrans":[0.653, 0.732, 0.584, 0.856, 0.784, 0.792, 0.828],
     "FT-Trans":[0.662, 0.824, 0.626, 0.892, 0.768, 0.840, 0.889],
     "Vime":[0.621, 0.697, 0.571, 0.892, 0.769, 0.803, 0.881],
     "Scarf":[0.651, 0.753, 0.556, 0.891, 0.703, 0.829,0.887],
     "TransTab":[0.741, 0.879, 0.665, 0.894, 0.791, 0.841, 0.897]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
df.mean(axis=0).sort_values()

TransTab    1.142857
DCN         2.571429
FT-Trans    4.000000
AutoInt     4.142857
XGBoost     5.857143
Scarf       6.714286
Vime        7.428571
TabTrans    7.714286
LR          8.857143
MLP         9.142857
SNN         9.428571
TabNet      9.857143
dtype: float64

# Transfer learning

In [ ]:
d = {
     "LR":[ 0.69, 0.69, 0.81, 0.82, 0.47, 0.56, 0.81, 0.81, 0.68, 0.78, 0.77, 0.82, 0.81, 0.84],
     "XGBoost":[0.72,0.71,0.85,0.87,0.46,0.63,0.88,0.89,0.80,0.81,0.76,0.82,0.92,0.91],
     "MLP":[0.67,0.70,0.82,0.86,0.53,0.67,0.89,0.90,0.73,0.82,0.79,0.83,0.90,0.90],
     "SNN":[0.66,0.63,0.85,0.83,0.54,0.42,0.87,0.88,0.57,0.54,0.77,0.82,0.87,0.88],
     "TabNet":[0.60,0.47,0.66,0.68,0.54,0.53,0.87,0.88,0.58,0.62,0.75,0.83,0.88,0.89],
     "DCN":[0.69,0.70,0.83,0.85,0.51,0.58,0.88,0.74,0.79,0.78,0.79,0.76,0.91,0.90],
     "AutoInt":[0.70,0.70,0.82,0.86,0.49,0.55,0.88,0.74,0.77,0.79,0.79,0.76,0.91,0.90],
     "TabTrans":[0.72,0.72,0.84,0.86,0.54,0.57,0.88,0.90,0.73,0.79,0.78,0.81,0.88,0.88],
     "FT-Trans":[0.72,0.71,0.83,0.85,0.53,0.64,0.89,0.90,0.76,0.79,0.78,0.84,0.91,0.91],
     "Vime":[0.59,0.70,0.79,0.76,0.45,0.53,0.88,0.90,0.65,0.81,0.58,0.83,0.90,0.90],
     "Scarf":[0.69,0.72,0.82,0.85,0.55,0.64,0.88,0.89,0.77,0.73,0.78,0.83,0.90,0.89],
     "TransTab":[0.74,0.76,0.87,0.89,0.55,0.66,0.88,0.90,0.80,0.80,0.79,0.84,0.91,0.91]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
print(df.mean(axis=0).sort_values())
print(df.std(axis=0).sort_values())
df

TransTab    1.500000
FT-Trans    3.428571
MLP         4.000000
XGBoost     4.071429
Scarf       5.000000
TabTrans    5.071429
DCN         5.714286
AutoInt     5.714286
Vime        7.357143
SNN         8.928571
TabNet      9.357143
LR          9.428571
dtype: float64
TransTab    0.940540
LR          1.869360
FT-Trans    2.064882
Scarf       2.480695
MLP         2.801099
TabNet      3.002746
DCN         3.049050
TabTrans    3.049950
SNN         3.149219
AutoInt     3.244607
XGBoost     3.315796
Vime        4.180672
dtype: float64

,LR,XGBoost,MLP,SNN,TabNet,DCN,AutoInt,TabTrans,FT-Trans,Vime,Scarf,TransTab
0,6.0,2.0,9.0,10.0,11.0,6.0,5.0,2.0,2.0,12.0,6.0,1.0
1,10.0,4.0,6.0,11.0,12.0,6.0,6.0,2.0,4.0,6.0,2.0,1.0
2,10.0,2.0,7.0,2.0,12.0,5.0,7.0,4.0,5.0,11.0,7.0,1.0
3,10.0,2.0,3.0,9.0,12.0,6.0,3.0,3.0,6.0,11.0,6.0,1.0
4,10.0,11.0,6.0,3.0,3.0,8.0,9.0,3.0,6.0,12.0,1.0,1.0
5,8.0,5.0,1.0,12.0,10.0,6.0,9.0,7.0,3.0,10.0,3.0,2.0
6,12.0,3.0,1.0,10.0,10.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0
7,10.0,6.0,1.0,8.0,8.0,11.0,11.0,1.0,1.0,1.0,6.0,1.0
8,9.0,1.0,7.0,12.0,11.0,3.0,4.0,7.0,6.0,10.0,4.0,1.0
9,8.0,2.0,1.0,12.0,11.0,8.0,5.0,5.0,5.0,2.0,10.0,4.0
10,8.0,10.0,1.0,8.0,11.0,1.0,1.0,5.0,5.0,12.0,5.0,1.0
11,7.0,7.0,3.0,7.0,3.0,11.0,11.0,10.0,1.0,3.0,3.0,1.0
12,12.0,1.0,6.0,11.0,9.0,2.0,2.0,9.0,2.0,6.0,6.0,2.0
13,12.0,1.0,4.0,10.0,8.0,4.0,4.0,10.0,1.0,4.0,8.0,1.0

In [ ]:
d = {
     "LR":[ 0.69, 0.69, 0.81, 0.82, 0.47, 0.56, 0.81, 0.81, 0.68, 0.78, 0.77, 0.82, 0.81, 0.84],
     "XGBoost":[0.72,0.71,0.85,0.87,0.46,0.63,0.88,0.89,0.80,0.81,0.76,0.82,0.92,0.91],
     "MLP":[0.67,0.70,0.82,0.86,0.53,0.67,0.89,0.90,0.73,0.82,0.79,0.83,0.90,0.90],
     "SNN":[0.66,0.63,0.85,0.83,0.54,0.42,0.87,0.88,0.57,0.54,0.77,0.82,0.87,0.88],
     "TabNet":[0.60,0.47,0.66,0.68,0.54,0.53,0.87,0.88,0.58,0.62,0.75,0.83,0.88,0.89],
     "DCN":[0.69,0.70,0.83,0.85,0.51,0.58,0.88,0.74,0.79,0.78,0.79,0.76,0.91,0.90],
     "AutoInt":[0.70,0.70,0.82,0.86,0.49,0.55,0.88,0.74,0.77,0.79,0.79,0.76,0.91,0.90],
     "TabTrans":[0.72,0.72,0.84,0.86,0.54,0.57,0.88,0.90,0.73,0.79,0.78,0.81,0.88,0.88],
     "FT-Trans":[0.72,0.71,0.83,0.85,0.53,0.64,0.89,0.90,0.76,0.79,0.78,0.84,0.91,0.91],
     "Vime":[0.59,0.70,0.79,0.76,0.45,0.53,0.88,0.90,0.65,0.81,0.58,0.83,0.90,0.90],
     "Scarf":[0.69,0.72,0.82,0.85,0.55,0.64,0.88,0.89,0.77,0.73,0.78,0.83,0.90,0.89],
     "TransTab":[0.70,0.72,0.83,0.92,0.58,0.62,0.89,0.89,0.81,0.78,0.81,0.83,0.90,0.91]
}
df = pd.DataFrame(d)
x = df.to_numpy()
l = np.zeros_like(x)
for r in range(x.shape[0]):
  ranks = []
  for c in range(x.shape[1]):
    ranks.append(np.flip(np.sort(x[r, :])).tolist().index(x[r,c]) + 1)
  l[r] = ranks

df[df.columns] = l
print(df.mean(axis=0).sort_values())
print(df.std(axis=0).sort_values())
df

TransTab    2.785714
FT-Trans    3.142857
XGBoost     3.928571
MLP         3.928571
Scarf       4.785714
TabTrans    4.857143
DCN         5.714286
AutoInt     5.714286
Vime        7.285714
SNN         8.857143
TabNet      9.285714
LR          9.357143
dtype: float64
LR          1.945691
FT-Trans    2.070197
TransTab    2.118729
Scarf       2.547354
MLP         2.730576
DCN         2.867016
AutoInt     3.148347
TabNet      3.172686
TabTrans    3.231031
XGBoost     3.315796
SNN         3.324898
Vime        4.232267
dtype: float64

,LR,XGBoost,MLP,SNN,TabNet,DCN,AutoInt,TabTrans,FT-Trans,Vime,Scarf,TransTab
0,6.0,1.0,9.0,10.0,11.0,6.0,4.0,1.0,1.0,12.0,6.0,4.0
1,10.0,4.0,6.0,11.0,12.0,6.0,6.0,1.0,4.0,6.0,1.0,1.0
2,10.0,1.0,7.0,1.0,12.0,4.0,7.0,3.0,4.0,11.0,7.0,4.0
3,10.0,2.0,3.0,9.0,12.0,6.0,3.0,3.0,6.0,11.0,6.0,1.0
4,10.0,11.0,6.0,3.0,3.0,8.0,9.0,3.0,6.0,12.0,2.0,1.0
5,8.0,4.0,1.0,12.0,10.0,6.0,9.0,7.0,2.0,10.0,2.0,5.0
6,12.0,4.0,1.0,10.0,10.0,4.0,4.0,4.0,1.0,4.0,4.0,1.0
7,10.0,5.0,1.0,8.0,8.0,11.0,11.0,1.0,1.0,1.0,5.0,5.0
8,9.0,2.0,7.0,12.0,11.0,3.0,4.0,7.0,6.0,10.0,4.0,1.0
9,7.0,2.0,1.0,12.0,11.0,7.0,4.0,4.0,4.0,2.0,10.0,7.0
10,8.0,10.0,2.0,8.0,11.0,2.0,2.0,5.0,5.0,12.0,5.0,1.0
11,7.0,7.0,2.0,7.0,2.0,11.0,11.0,10.0,1.0,2.0,2.0,2.0
12,12.0,1.0,5.0,11.0,9.0,2.0,2.0,9.0,2.0,5.0,5.0,5.0
13,12.0,1.0,4.0,10.0,8.0,4.0,4.0,10.0,1.0,4.0,8.0,1.0